### PR TITLE
Update browse.py

### PR DESCRIPTION
**Pull request by 9acca9**
Browse artist

### CODE REVIEW

**Comment by vitiko98** [comment]
Thanks for the PRs! I'll review as soon as possible.

**Comment by 9acca9** [comment]
Oh, good. First time i make a pull request and it seems i did it wrong, because just with this is fine: 

https://github.com/vitiko98/mopidy-qobuz/pull/4

it seems, that in here, i repeat the pull request for the same file. Sorry for that.

**Comment by vitiko98** [comment]
@9acca9 please check the conflicts. I just merged your #4 PR

**Comment by 9acca9** [comment]
There is no need to merge this, was a mistake.

**Comment by vitiko98** [comment]
Are #2 and #3 related to your PR? If so, please close them.

**Pull request closed without merging**
